import { useEffect, useMemo, useState } from 'react';
import { FilePlus2, FileText, Mail, Printer, Trash2, ChevronLeft, Search, X, ShieldCheck, AlertTriangle, LockKeyhole, Check, CircleAlert, Plus, Copy } from 'lucide-react';
import { deleteContract, getContracts, saveContract } from './db';
import { SERVICE_OPTIONS, calculate, renderContract, validateContract } from './template';

const newPerformance = () => ({id:crypto.randomUUID(),date:'',venue:'',location:'',performanceTime:'',callTime:'',duration:'',sets:'1',breakMinutes:'',soundcheckIncluded:true,soundcheckMinutes:'30',fee:''});
const legacyPerformance = c => ({id:'legacy',date:c.eventDate||'',venue:c.venue||'',location:c.location||'',performanceTime:c.performanceTime||'',callTime:c.callTime||'',duration:c.duration||'',sets:c.sets||'1',breakMinutes:c.breakMinutes||'',soundcheckIncluded:c.soundcheckIncluded!==false,soundcheckMinutes:c.soundcheckMinutes||'30',fee:''});
const performanceRows = c => Array.isArray(c.performances)&&c.performances.length ? c.performances : [legacyPerformance(c)];
const compensationModel = c => c.compensationModel==='perPerformance'?'perPerformance':'package';

const blank = () => ({id:crypto.randomUUID(),number:`VA-${new Date().getFullYear()}-${Math.floor(1000+Math.random()*9000)}`,status:'draft',updatedAt:new Date().toISOString(),clientName:'',clientContact:'',clientEmail:'',clientPhone:'',artistName:'',artistEmail:'',artistPhone:'',artistBusinessName:'',artistAddress:'',eventName:'',eventDate:'',venue:'',location:'',performanceTime:'',callTime:'',duration:'',sets:'1',breakMinutes:'',performances:[newPerformance()],services:['Vocal Performance'],compensationModel:'package',performanceFee:'',depositAmount:'',depositDue:'',balanceDue:'Before performance',rehearsalRate:'20',overtimeRate:'',travelAmount:'',accommodationAmount:'',perDiem:'',mileageRate:'',parkingAmount:'',travelProvided:false,accommodationProvided:false,singleOccupancy:true,rehearsals:[],cancellationSchedule:'standard',cancellationCustom:'',allowPhotography:false,allowVideo:false,allowLivestream:false,allowBroadcast:false,allowPromoClips:false,allowCommercialUse:false,allowAI:false,allowVoiceCloning:false,mediaCompensation:'',soundcheckIncluded:true,soundcheckMinutes:'30',dressingRoomRequired:false,venueContact:'',productionContact:'',safetyRequirements:'',governingJurisdiction:'Alberta, Canada',additionalTerms:''});

function strengthCheck(c){
  const rows=performanceRows(c), model=compensationModel(c), perfTotal=model==='perPerformance'?rows.reduce((s,r)=>s+Number(r.fee||0),0):Number(c.performanceFee||0);
  const checks=[
    {key:'parties',label:'Both parties identified',detail:'Client name/email and artist name are present.',ok:!!c.clientName?.trim()&&!!c.clientEmail?.trim()&&!!c.artistName?.trim(),weight:10,required:true},
    {key:'event',label:'Performance schedule is clearly defined',detail:`${rows.length>1?`${rows.length} tour dates are scheduled.`:'Event, date, venue and performance time are specified.'}`,ok:!!c.eventName?.trim()&&rows.length>0&&rows.every(r=>!!r.date&&!!r.venue?.trim()&&!!r.location?.trim()&&!!r.performanceTime),weight:12,required:true},
    {key:'scope',label:'Scope and services are defined',detail:'At least one service is selected.',ok:Array.isArray(c.services)&&c.services.length>0,weight:8,required:true},
    {key:'fee',label:'Compensation is fully allocated',detail:model==='perPerformance'?'Every performance has its own positive fee.':'A positive package performance fee is defined.',ok:perfTotal>0&&(model==='package'||rows.every(r=>Number(r.fee||0)>0)),weight:12,required:true},
    {key:'payment',label:'Payment timing is protected',detail:'Balance timing is specified and any deposit has a due date within the stated compensation.',ok:!!c.balanceDue&&(!c.depositAmount||!!c.depositDue),weight:9,required:true},
    {key:'overtime',label:'Additional time is priced',detail:'Additional performance/rehearsal/soundcheck time has a rate.',ok:Number(c.overtimeRate||0)>0&&Number(c.rehearsalRate||0)>=0,weight:7,required:true},
    {key:'cancellation',label:'Cancellation protection is defined',detail:'Standard artist-protective schedule or custom terms are selected.',ok:c.cancellationSchedule==='standard'||(c.cancellationSchedule==='custom'&&!!c.cancellationCustom?.trim()),weight:11,required:true},
    {key:'media',label:'Media rights are intentionally controlled',detail:'Commercial use has compensation and AI/voice permissions remain explicitly reviewed.',ok:(!c.allowCommercialUse||Number(c.mediaCompensation||0)>0)&&!c.allowAI&&!c.allowVoiceCloning,weight:11,required:true},
    {key:'safety',label:'Safety and venue responsibility are addressed',detail:'The agreement contains the safety clause; contacts and requirements strengthen the deal.',ok:true,weight:5,required:false},
    {key:'travel',label:'Tour travel responsibilities are addressed',detail:'For multi-date work, add travel/accommodation terms or confirm they are not required.',ok:rows.length===1||!!c.travelAmount||!!c.accommodationAmount||!!c.perDiem||!!c.travelProvided||!!c.accommodationProvided,weight:5,required:false},
    {key:'jurisdiction',label:'Governing jurisdiction is specified',detail:'The contract identifies the governing jurisdiction.',ok:!!c.governingJurisdiction?.trim(),weight:5,required:true},
    {key:'ai',label:'AI / voice rights remain restricted',detail:'AI training and voice cloning require a separate lawyer-reviewed rider.',ok:!c.allowAI&&!c.allowVoiceCloning,weight:3,required:true},
    {key:'commercial',label:'Commercial media is compensated',detail:'Commercial advertising use requires stated additional compensation.',ok:!c.allowCommercialUse||Number(c.mediaCompensation||0)>0,weight:2,required:true}
  ];
  const totalWeight=checks.reduce((s,x)=>s+x.weight,0), score=Math.round(checks.reduce((s,x)=>s+(x.ok?x.weight:0),0)/totalWeight*100);
  return {score,checks,blockers:checks.filter(x=>x.required&&!x.ok),warnings:checks.filter(x=>!x.required&&!x.ok)};
}

function App(){
  const [contracts,setContracts]=useState([]),[active,setActive]=useState(null),[view,setView]=useState('drafts'),[saved,setSaved]=useState(true),[query,setQuery]=useState('');
  useEffect(()=>{getContracts().then(setContracts).catch(()=>{});},[]);
  const drafts=contracts.filter(c=>c.status==='draft'),finalized=contracts.filter(c=>c.status!=='draft');
  const filtered=(view==='drafts'?drafts:finalized).filter(c=>`${c.clientName} ${c.artistName} ${c.eventName}`.toLowerCase().includes(query.toLowerCase()));
  async function persist(next){const withTime={...next,updatedAt:new Date().toISOString()};setActive(withTime);setSaved(false);await saveContract(withTime);setContracts(await getContracts());setSaved(true);}
  function newContract(){setActive(blank());setView('editor');setSaved(false)}
  function edit(c){setActive(c);setView('editor');setSaved(true)}
  async function remove(id){if(!confirm('Delete this contract draft?'))return;await deleteContract(id);setContracts(await getContracts());if(active?.id===id)setActive(null)}
  async function finalize(){if(!active)return;const report=strengthCheck(active),hard=validateContract(active);const issues=[...new Set([...report.blockers.map(x=>x.label),...hard])];if(issues.length){setActive({...active,_strengthOpen:true});return}const next={...active,status:'finalized',updatedAt:new Date().toISOString()};await saveContract(next);setContracts(await getContracts());setActive(next);setSaved(true)}
  function print(){window.print()}
  function gmail(){if(!active)return;const subject=encodeURIComponent(`Vocal Artist Agreement — ${active.artistName||'Artist'} — ${active.eventName||'Event'}`),body=encodeURIComponent(`Hello ${active.clientContact||active.clientName||''},\n\nPlease find the vocal artist agreement for ${active.eventName||'the event'} attached.\n\nPlease review the agreement and let me know if you have any questions.\n\nBest,`);window.open(`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(active.clientEmail||'')}&su=${subject}&body=${body}`,'_blank')}
  if(!active||view!=='editor')return <Dashboard contracts={filtered} query={query} setQuery={setQuery} view={view} setView={setView} newContract={newContract} edit={edit} remove={remove}/>;
  return <Editor contract={active} persist={persist} saved={saved} back={()=>{setView(active.status==='draft'?'drafts':'finalized');setActive(null)}} finalize={finalize} print={print} gmail={gmail}/>;
}

function Dashboard({contracts,query,setQuery,view,setView,newContract,edit,remove}){return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">VC</div><div><strong>Vocal Contracts</strong><span>Artist agreement workspace</span></div></div><button className="primary" onClick={newContract}><FilePlus2 size={17}/> New contract</button></header><main className="dashboard"><div className="dash-heading"><p className="eyebrow">WORKSPACE</p><h1>Contracts</h1><p className="muted">Create, save and prepare professional vocal artist agreements.</p></div><div className="tabs"><button className={view==='drafts'?'active':''} onClick={()=>setView('drafts')}>Drafts <b>{contracts.length}</b></button><button className={view==='finalized'?'active':''} onClick={()=>setView('finalized')}>Finalized</button><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contracts"/>{query&&<X size={15} onClick={()=>setQuery('')}/>}</label></div>{contracts.length===0?<div className="empty"><FileText size={34}/><h2>{view==='drafts'?'No drafts yet':'No finalized contracts yet'}</h2><p>Start a new contract and your work will be saved locally in this browser.</p><button className="primary" onClick={newContract}><FilePlus2 size={17}/> Create contract</button></div>:<div className="contract-list">{contracts.map(c=><div className="contract-row" key={c.id} onClick={()=>edit(c)}><div className="doc-icon"><FileText size={19}/></div><div className="row-main"><strong>{c.eventName||'Untitled event'}</strong><span>{c.artistName||'Artist not set'} · {c.clientName||'Client not set'}</span></div><div className="row-meta"><span>{c.status==='draft'?'Draft':'Finalized'}</span><small>{new Date(c.updatedAt).toLocaleDateString()}</small></div><button className="icon-btn danger" onClick={e=>{e.stopPropagation();remove(c.id)}}><Trash2 size={16}/></button></div>)}</div>}</main></div>}

function Editor({contract,persist,saved,back,finalize,print,gmail}){
  const totals=useMemo(()=>calculate(contract),[contract]),report=useMemo(()=>strengthCheck(contract),[contract]),validation=useMemo(()=>validateContract(contract),[contract]);
  const update=(key,value)=>persist({...contract,[key]:value});
  const jumpToSection=id=>{const target=document.getElementById(id);if(!target)return;target.scrollIntoView({behavior:'smooth',block:'start'});target.classList.remove('strength-target');requestAnimationFrame(()=>{target.classList.add('strength-target');window.setTimeout(()=>target.classList.remove('strength-target'),1400)})};
  const rows=performanceRows(contract),model=compensationModel(contract);
  const syncFirst=next=>{const first=next[0]||newPerformance();return {...contract,performances:next,eventDate:first.date,venue:first.venue,location:first.location,performanceTime:first.performanceTime,callTime:first.callTime,duration:first.duration,sets:first.sets,breakMinutes:first.breakMinutes,soundcheckIncluded:first.soundcheckIncluded,soundcheckMinutes:first.soundcheckMinutes}};
  const updatePerformance=(i,key,value)=>persist(syncFirst(rows.map((r,index)=>index===i?{...r,[key]:value}:r)));
  const addPerformance=()=>persist({...contract,performances:[...rows,newPerformance()]});
  const duplicatePerformance=i=>persist({...contract,performances:[...rows,{...rows[i],id:crypto.randomUUID(),fee:model==='perPerformance'?rows[i].fee:''}]});
  const removePerformance=i=>{if(rows.length===1)return;persist(syncFirst(rows.filter((_,index)=>index!==i)))};
  const toggleService=s=>update('services',contract.services.includes(s)?contract.services.filter(x=>x!==s):[...contract.services,s]);
  const addRehearsal=()=>update('rehearsals',[...contract.rehearsals,{id:crypto.randomUUID(),date:'',start:'',end:'',hours:''}]);
  const updateRehearsal=(id,key,value)=>update('rehearsals',contract.rehearsals.map(r=>r.id===id?{...r,[key]:value}:r));
  const removeRehearsal=id=>update('rehearsals',contract.rehearsals.filter(r=>r.id!==id));
  const mediaCount=['allowPhotography','allowVideo','allowLivestream','allowBroadcast','allowPromoClips','allowCommercialUse','allowAI','allowVoiceCloning'].filter(k=>contract[k]).length;
  return <div className="editor-shell"><header className="editor-bar"><button className="back" onClick={back}><ChevronLeft size={18}/> Contracts</button><div className="editor-title"><strong>{contract.eventName||'New contract'}</strong><span>{saved?'Saved locally':'Saving…'}</span></div><div className="editor-actions"><button className="secondary" onClick={print}><Printer size={16}/> PDF / Print</button><button className="secondary" onClick={gmail}><Mail size={16}/> Gmail</button><button className="primary" onClick={finalize}><LockKeyhole size={16}/> Finalize</button></div></header><div className="workspace"><aside className="form-panel"><StrengthPanel report={report} validation={validation} onJump={jumpToSection}/>
    <Section id="client-section" title="Client information"><Field label="Client / organization *" value={contract.clientName} onChange={v=>update('clientName',v)}/><div className="two"><Field label="Contact name" value={contract.clientContact} onChange={v=>update('clientContact',v)}/><Field label="Email *" type="email" value={contract.clientEmail} onChange={v=>update('clientEmail',v)}/></div><Field label="Phone" value={contract.clientPhone} onChange={v=>update('clientPhone',v)}/></Section>
    <Section id="artist-section" title="Artist"><Field label="Artist name *" value={contract.artistName} onChange={v=>update('artistName',v)}/><div className="two"><Field label="Artist email" type="email" value={contract.artistEmail} onChange={v=>update('artistEmail',v)}/><Field label="Artist phone" value={contract.artistPhone} onChange={v=>update('artistPhone',v)}/></div><Field label="Artist / business name" value={contract.artistBusinessName} onChange={v=>update('artistBusinessName',v)}/><Field label="Artist address" value={contract.artistAddress} onChange={v=>update('artistAddress',v)}/></Section>
    <Section id="event-section" title="Event & performance"><Field label="Tour / event name *" value={contract.eventName} onChange={v=>update('eventName',v)}/><p className="helper">Build the complete schedule first. Every date, venue, city and performance time becomes an independent line item in the agreement.</p><div className="performance-schedule">{rows.map((r,i)=><div className="performance-card" key={r.id}><div className="performance-card-head"><div><span className="performance-label">PERFORMANCE {String(i+1).padStart(2,'0')}</span><strong>{r.date?new Date(`${r.date}T12:00:00`).toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'}):'New date'}{r.venue?` · ${r.venue}`:''}</strong></div><div className="performance-card-actions"><button type="button" className="icon-btn" onClick={()=>duplicatePerformance(i)} title="Duplicate date"><Copy size={14}/></button>{rows.length>1&&<button type="button" className="icon-btn danger" onClick={()=>removePerformance(i)} title="Remove date"><Trash2 size={14}/></button>}</div></div><div className="two"><Field label="Performance date *" type="date" value={r.date} onChange={v=>updatePerformance(i,'date',v)}/><Field label="Performance time *" type="time" value={r.performanceTime} onChange={v=>updatePerformance(i,'performanceTime',v)}/></div><div className="two"><Field label="Venue *" value={r.venue} onChange={v=>updatePerformance(i,'venue',v)}/><Field label="City / location *" value={r.location} onChange={v=>updatePerformance(i,'location',v)}/></div><div className="two"><Field label="Call time" type="time" value={r.callTime} onChange={v=>updatePerformance(i,'callTime',v)}/><Field label="Performance duration" placeholder="e.g. 90 minutes" value={r.duration} onChange={v=>updatePerformance(i,'duration',v)}/></div><div className="two"><Field label="Number of sets" type="number" min="1" value={r.sets} onChange={v=>updatePerformance(i,'sets',v)}/><Field label="Break between sets (min)" type="number" value={r.breakMinutes} onChange={v=>updatePerformance(i,'breakMinutes',v)}/></div>{model==='perPerformance'&&<Field label="Performance fee (CAD) *" type="number" min="0" value={r.fee} onChange={v=>updatePerformance(i,'fee',v)}/>}<div className="toggle-row"><Toggle label="Soundcheck included" checked={r.soundcheckIncluded} onChange={v=>updatePerformance(i,'soundcheckIncluded',v)}/><Toggle label="Dressing room required" checked={contract.dressingRoomRequired} onChange={v=>update('dressingRoomRequired',v)}/></div>{r.soundcheckIncluded&&<Field label="Included soundcheck time (minutes)" type="number" value={r.soundcheckMinutes} onChange={v=>updatePerformance(i,'soundcheckMinutes',v)}/>}</div>)}<button type="button" className="add-row" onClick={addPerformance}><Plus size={14}/> Add another performance date</button></div></Section>
    <Section id="services-section" title="Services"><p className="helper">Select every service included in this agreement. Unselected services are not included.</p><div className="service-grid">{SERVICE_OPTIONS.map(s=><button type="button" className={`service ${contract.services.includes(s)?'selected':''}`} onClick={()=>toggleService(s)} key={s}><span>{contract.services.includes(s)?'✓':'+'}</span>{s}</button>)}</div></Section>
    <Section id="payment-section" title="Compensation & payment"><SelectField label="Compensation model" value={model} onChange={v=>update('compensationModel',v)} options={['package','perPerformance']} labels={{package:'Package fee — one total for the engagement',perPerformance:'Per performance — each date has its own fee'}}/><p className="helper">{model==='package'?'Use one fee when the artist is booked for the tour/event as a package.':'Use individual fees when dates or venues have different compensation.'}</p>{model==='package'&&<Field label="Package performance fee (CAD) *" type="number" min="0" value={contract.performanceFee} onChange={v=>update('performanceFee',v)}/>}<div className="two"><Field label="Deposit / retainer (CAD)" type="number" min="0" value={contract.depositAmount} onChange={v=>update('depositAmount',v)}/><Field label="Deposit due" type="date" value={contract.depositDue} onChange={v=>update('depositDue',v)}/></div><SelectField label="Balance due" value={contract.balanceDue} onChange={v=>update('balanceDue',v)} options={['Before performance','Event date','Within 7 days','Within 14 days','Within 30 days']}/><div className="two"><Field label="Rehearsal rate / hour (CAD) *" type="number" min="0" value={contract.rehearsalRate} onChange={v=>update('rehearsalRate',v)}/><Field label="Overtime / additional time rate (CAD) *" type="number" min="0" value={contract.overtimeRate} onChange={v=>update('overtimeRate',v)}/></div><p className="helper">Unscheduled performance, rehearsal, soundcheck, waiting, or other requested time is additional work.</p><div className="total-card"><span>Estimated stated compensation</span><strong>${totals.total.toFixed(2)} CAD</strong></div></Section>
    <Section id="cancellation-section" title="Cancellation & postponement"><SelectField label="Client cancellation schedule" value={contract.cancellationSchedule} onChange={v=>update('cancellationSchedule',v)} options={['standard','custom']} labels={{standard:'Artist-protective: 50% / 75% / 100%',custom:'Custom schedule'}}/>{contract.cancellationSchedule==='custom'&&<Field label="Custom cancellation terms" value={contract.cancellationCustom} onChange={v=>update('cancellationCustom',v)} placeholder="State the exact amounts or percentages due at each notice period."/>}<div className="notice-card"><ShieldCheck size={16}/><span>Each scheduled date is treated separately for cancellation. A cancelled date does not automatically cancel the rest of the tour.</span></div></Section>
    <Section id="media-section" title="Media & recording rights"><p className="helper">Permissions default to OFF. Enable only what has actually been negotiated. AI and voice cloning require a separate lawyer-reviewed rider.</p><div className="toggle-list"><Toggle label="Event photography" checked={contract.allowPhotography} onChange={v=>update('allowPhotography',v)}/><Toggle label="Video recording" checked={contract.allowVideo} onChange={v=>update('allowVideo',v)}/><Toggle label="Livestreaming" checked={contract.allowLivestream} onChange={v=>update('allowLivestream',v)}/><Toggle label="Broadcast / retransmission" checked={contract.allowBroadcast} onChange={v=>update('allowBroadcast',v)}/><Toggle label="Short promotional clips" checked={contract.allowPromoClips} onChange={v=>update('allowPromoClips',v)}/><Toggle label="Commercial advertising use" checked={contract.allowCommercialUse} onChange={v=>update('allowCommercialUse',v)}/><Toggle label="AI training / generative AI use" checked={contract.allowAI} onChange={v=>update('allowAI',v)}/><Toggle label="Voice cloning / digital replica" checked={contract.allowVoiceCloning} onChange={v=>update('allowVoiceCloning',v)}/></div><Field label="Additional media compensation (CAD)" type="number" min="0" value={contract.mediaCompensation} onChange={v=>update('mediaCompensation',v)}/><p className="helper">{mediaCount===0?'Protected default: no recording, broadcast, commercial exploitation, AI use, or voice cloning is authorized.':`${mediaCount} media permission${mediaCount===1?' is':'s are'} enabled; review the scope before finalizing.`}</p></Section>
    <Section id="travel-section" title="Travel & accommodation"><div className="two"><Field label="Travel / expenses (CAD)" type="number" min="0" value={contract.travelAmount} onChange={v=>update('travelAmount',v)}/><Field label="Accommodation (CAD)" type="number" min="0" value={contract.accommodationAmount} onChange={v=>update('accommodationAmount',v)}/></div><div className="two"><Field label="Per diem / meals (CAD)" type="number" min="0" value={contract.perDiem} onChange={v=>update('perDiem',v)}/><Field label="Mileage rate (CAD / km)" type="number" min="0" step="0.01" value={contract.mileageRate} onChange={v=>update('mileageRate',v)}/></div><Field label="Parking / other approved travel (CAD)" type="number" min="0" value={contract.parkingAmount} onChange={v=>update('parkingAmount',v)}/><div className="toggle-row"><Toggle label="Client provides transportation" checked={contract.travelProvided} onChange={v=>update('travelProvided',v)}/><Toggle label="Client provides accommodation" checked={contract.accommodationProvided} onChange={v=>update('accommodationProvided',v)}/></div><Toggle label="Single-occupancy accommodation" checked={contract.singleOccupancy} onChange={v=>update('singleOccupancy',v)}/></Section>
    <Section id="safety-section" title="Venue, production & safety"><div className="two"><Field label="Venue contact" value={contract.venueContact} onChange={v=>update('venueContact',v)}/><Field label="Production contact" value={contract.productionContact} onChange={v=>update('productionContact',v)}/></div><Field label="Safety / production requirements" value={contract.safetyRequirements} onChange={v=>update('safetyRequirements',v)} placeholder="Stage, security, access, sound, power, permits, etc."/><Field label="Governing jurisdiction *" value={contract.governingJurisdiction} onChange={v=>update('governingJurisdiction',v)}/></Section>
    <Section id="additional-section" title="Additional terms"><textarea value={contract.additionalTerms} onChange={e=>update('additionalTerms',e.target.value)} placeholder="Only add negotiated terms here. The protected core clauses are already included."/></Section>
  </aside><main className="preview-panel"><div className="preview-label"><span>LIVE PREVIEW</span><small>Print-ready contract</small></div><div dangerouslySetInnerHTML={{__html:renderContract(contract)}}/></main></div></div>
}

function StrengthPanel({report,validation,onJump}){const targets={parties:'client-section',event:'event-section',scope:'services-section',fee:'payment-section',payment:'payment-section',overtime:'payment-section',cancellation:'cancellation-section',media:'media-section',safety:'safety-section',travel:'travel-section',jurisdiction:'safety-section',ai:'media-section',commercial:'media-section'};const blockerLabels=[...new Set([...report.blockers.map(x=>x.label),...validation])];return <div className={`strength-panel ${blockerLabels.length?'needs-work':'ready'}`}><div className="strength-head"><div><p className="eyebrow">CONTRACT STRENGTH CHECK</p><strong>{blockerLabels.length?'Not ready to finalize':'Ready to finalize'}</strong></div><div className="strength-score"><span>{report.score}</span><small>/100</small></div></div><div className="strength-bar"><span style={{width:`${report.score}%`}}/></div>{blockerLabels.length>0&&<div className="strength-alert"><AlertTriangle size={15}/><div><strong>Protection gaps must be resolved</strong><span>{blockerLabels.length} unique item{blockerLabels.length===1?'':'s'} blocking finalization.</span></div></div>}<div className="strength-list">{report.checks.map(item=><button type="button" className={`strength-item ${item.ok?'ok':'warn'}`} key={item.key} onClick={()=>onJump(targets[item.key]||'additional-section')} title={item.ok?'Review this section':'Fix this item'}><span className="strength-icon">{item.ok?<Check size={14}/>:<CircleAlert size={14}/>}</span><span className="strength-copy"><strong>{item.label}</strong><span>{item.detail}</span></span><span className="strength-action">{item.ok?'Review':'Fix'}</span></button>)}{validation.filter(v=>!report.checks.some(x=>!x.ok&&x.label===v)).map(v=><button type="button" className="strength-item warn" key={v} onClick={()=>onJump('payment-section')}><span className="strength-icon"><CircleAlert size={14}/></span><span className="strength-copy"><strong>{v}</strong><span>Validation requirement</span></span><span className="strength-action">Fix</span></button>)}</div><p className="strength-note">This is a completeness safeguard, not a legal opinion. A strong score does not guarantee enforceability.</p></div>}
function Section({id,title,children}){return <section id={id} className="form-section"><h2>{title}</h2>{children}</section>}
function Field({label,value,onChange,type='text',placeholder='',min,step}){return <label className="field"><span>{label}</span><input type={type} min={min} step={step} value={value??''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,onChange,options,labels={}}){return <label className="field"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{labels[o]||o}</option>)}</select></label>}
function Toggle({label,checked,onChange}){return <label className="toggle"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-ui"/><span>{label}</span></label>}
export default App;
