import { useEffect, useMemo, useState } from 'react';
import { FilePlus2, FileText, Mail, Printer, Trash2, ChevronLeft, Search, X, ShieldCheck, AlertTriangle, LockKeyhole, Check, CircleAlert, Plus, Copy, LayoutDashboard, Send, BarChart3 } from 'lucide-react';
import { deleteContract, getContracts, saveContract } from './db';
import { SERVICE_OPTIONS, calculate, renderContract, validateContract } from './template';

const newPerformance = () => ({id:crypto.randomUUID(),date:'',venue:'',location:'',performanceTime:'',callTime:'',duration:'',sets:'1',breakMinutes:'',soundcheckIncluded:true,soundcheckMinutes:'30',fee:''});
const legacyPerformance = c => ({id:'legacy',date:c.eventDate||'',venue:c.venue||'',location:c.location||'',performanceTime:c.performanceTime||'',callTime:c.callTime||'',duration:c.duration||'',sets:c.sets||'1',breakMinutes:c.breakMinutes||'',soundcheckIncluded:c.soundcheckIncluded!==false,soundcheckMinutes:c.soundcheckMinutes||'30',fee:''});
const performanceRows = c => Array.isArray(c.performances)&&c.performances.length ? c.performances : [legacyPerformance(c)];
const compensationModel = c => c.compensationModel==='perPerformance'?'perPerformance':'package';

const blank = () => ({id:crypto.randomUUID(),number:`VA-${new Date().getFullYear()}-${Math.floor(1000+Math.random()*9000)}`,status:'draft',updatedAt:new Date().toISOString(),clientName:'',clientContact:'',clientEmail:'',clientPhone:'',artistName:'',artistEmail:'',artistPhone:'',artistBusinessName:'',artistAddress:'',eventName:'',eventDate:'',venue:'',location:'',performanceTime:'',callTime:'',duration:'',sets:'1',breakMinutes:'',performances:[newPerformance()],services:['Vocal Performance'],compensationModel:'package',performanceFee:'',depositAmount:'',depositDue:'',balanceDue:'Before performance',rehearsalRate:'20',overtimeRate:'',travelAmount:'',accommodationAmount:'',perDiem:'',mileageRate:'',parkingAmount:'',travelProvided:false,accommodationProvided:false,singleOccupancy:true,rehearsals:[],cancellationSchedule:'standard',cancellationCustom:'',allowPhotography:false,allowVideo:false,allowLivestream:false,allowBroadcast:false,allowPromoClips:false,allowCommercialUse:false,allowAI:false,allowVoiceCloning:false,mediaCompensation:'',soundcheckIncluded:true,soundcheckMinutes:'30',dressingRoomRequired:false,venueContact:'',productionContact:'',safetyRequirements:'',governingJurisdiction:'Alberta, Canada',additionalTerms:''});

function strengthCheck(c){
  const rows=performanceRows(c), model=compensationModel(c), perfTotal=model==='perPerformance'?rows.reduce((s,r)=>s+Number(r.fee||0),0):Number(c.performanceFee||0);
  const checks=[
    {key:'parties',label:'Both parties identified',detail:'Client name/email and artist name are present.',ok:!!c.clientName?.trim()&&!!c.clientEmail?.trim()&&!!c.artistName?.trim(),weight:10,required:true},
    {key:'event',label:'Performance schedule is clearly defined',detail:`${rows.length>1?`${rows.length} tour dates are scheduled.`:'Event, date, venue and performance time are specified.'}`,ok:!!c.eventName?.trim()&&rows.length>0&&rows.every(r=>!!r.date&&!!r.venue?.trim()&&!!r.location?.trim()&&!!r.performanceTime),weight:12,required:true},
    {key:'scope',label:'Scope and services are defined',detail:'At least one service is selected.',ok:Array.isArray(c.services)&&c.services.length>0,weight:8,required:true},
    {key:'fee',label:'Compensation is fully allocated',detail:model==='perPerformance'?'Every performance has its own positive fee.':'A positive package performance fee is defined.',ok:perfTotal>0&&(model==='package'||rows.every(r=>Number(r.fee||0)>0)),weight:12,required:true},
    {key:'payment',label:'Payment timing is protected',detail:'Balance timing is specified and any deposit has a due date within the stated compensation.',ok:!!c.balanceDue&&(!c.depositAmount||!!c.depositDue),weight:9,required:true},
    {key:'overtime',label:'Additional time is priced',detail:'Additional performance/rehearsal/soundcheck time has a rate.',ok:Number(c.overtimeRate||0)>0&&Number(c.rehearsalRate||0)>=0,weight:7,required:true},
    {key:'cancellation',label:'Cancellation protection is defined',detail:'Standard artist-protective schedule or custom terms are selected.',ok:c.cancellationSchedule==='standard'||(c.cancellationSchedule==='custom'&&!!c.cancellationCustom?.trim()),weight:11,required:true},
    {key:'media',label:'Media rights are intentionally controlled',detail:'Commercial use has compensation and AI/voice permissions remain explicitly reviewed.',ok:(!c.allowCommercialUse||Number(c.mediaCompensation||0)>0)&&!c.allowAI&&!c.allowVoiceCloning,weight:11,required:true},
    {key:'safety',label:'Safety and venue responsibility are addressed',detail:'The agreement contains the safety clause; contacts and requirements strengthen the deal.',ok:true,weight:5,required:false},
    {key:'travel',label:'Tour travel responsibilities are addressed',detail:'For multi-date work, add travel/accommodation terms or confirm they are not required.',ok:rows.length===1||!!c.travelAmount||!!c.accommodationAmount||!!c.perDiem||!!c.travelProvided||!!c.accommodationProvided,weight:5,required:false},
    {key:'jurisdiction',label:'Governing jurisdiction is specified',detail:'The contract identifies the governing jurisdiction.',ok:!!c.governingJurisdiction?.trim(),weight:5,required:true},
    {key:'ai',label:'AI / voice rights remain restricted',detail:'AI training and voice cloning require a separate lawyer-reviewed rider.',ok:!c.allowAI&&!c.allowVoiceCloning,weight:3,required:true},
    {key:'commercial',label:'Commercial media is compensated',detail:'Commercial advertising use requires stated additional compensation.',ok:!c.allowCommercialUse||Number(c.mediaCompensation||0)>0,weight:2,required:true}
  ];
  const totalWeight=checks.reduce((s,x)=>s+x.weight,0), score=Math.round(checks.reduce((s,x)=>s+(x.ok?x.weight:0),0)/totalWeight*100);
  return {score,checks,blockers:checks.filter(x=>x.required&&!x.ok),warnings:checks.filter(x=>!x.required&&!x.ok)};
}

function App(){
  const [contracts,setContracts]=useState([]),[active,setActive]=useState(null),[view,setView]=useState('overview'),[saved,setSaved]=useState(true),[query,setQuery]=useState('');
  useEffect(()=>{getContracts().then(setContracts).catch(()=>{});},[]);
  const drafts=contracts.filter(c=>c.status==='draft'), finalized=contracts.filter(c=>c.status==='finalized'||c.status==='sent'), sent=contracts.filter(c=>c.status==='sent');
  const filtered=(view==='drafts'?drafts:view==='finalized'?finalized:view==='sent'?sent:contracts).filter(c=>`${c.clientName} ${c.artistName} ${c.eventName}`.toLowerCase().includes(query.toLowerCase()));
  async function persist(next){const withTime={...next,updatedAt:new Date().toISOString()};setActive(withTime);setSaved(false);await saveContract(withTime);setContracts(await getContracts());setSaved(true);}
  function newContract(){setActive(blank());setView('drafts');setSaved(false)}
  function edit(c){setActive(c);setView(c.status==='sent'?'sent':c.status==='finalized'?'finalized':'drafts');setSaved(true)}
  async function remove(id){if(!confirm('Delete this contract draft?'))return;await deleteContract(id);setContracts(await getContracts());if(active?.id===id)setActive(null)}
  async function finalize(){if(!active)return;const report=strengthCheck(active),hard=validateContract(active);const issues=[...new Set([...report.blockers.map(x=>x.label),...hard])];if(issues.length){setActive({...active,_strengthOpen:true});return}const next={...active,status:'finalized',updatedAt:new Date().toISOString()};await saveContract(next);setContracts(await getContracts());setActive(next);setSaved(true)}
  function print(){window.print()}
  function gmail(){if(!active)return;const subject=encodeURIComponent(`Vocal Artist Agreement — ${active.artistName||'Artist'} — ${active.eventName||'Event'}`),body=encodeURIComponent(`Hello ${active.clientContact||active.clientName||''},\n\nPlease find the vocal artist agreement for ${active.eventName||'the event'} attached.\n\nPlease review the agreement and let me know if you have any questions.\n\nBest,`);window.open(`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(active.clientEmail||'')}&su=${subject}&body=${body}`,'_blank')}
  if(!active||view==='overview')return <Dashboard contracts={filtered} allContracts={contracts} query={query} setQuery={setQuery} view={view} setView={setView} newContract={newContract} edit={edit} remove={remove}/>;
  return <Editor contract={active} persist={persist} saved={saved} back={()=>{setView('overview');setActive(null)}} finalize={finalize} print={print} gmail={gmail}/>;
}

function Dashboard({contracts,allContracts,query,setQuery,view,setView,newContract,edit,remove}){
  const drafts=allContracts.filter(c=>c.status==='draft').length, finalized=allContracts.filter(c=>c.status==='finalized').length, sent=allContracts.filter(c=>c.status==='sent').length;
  const booked=allContracts.filter(c=>c.status!=='draft').reduce((sum,c)=>sum+Number(c.performanceFee||0)+(Array.isArray(c.performances)&&c.compensationModel==='perPerformance'?c.performances.reduce((s,p)=>s+Number(p.fee||0),0):0),0);
  const upcoming=allContracts.flatMap(c=>performanceRows(c).map(r=>({contract:c,date:r.date,venue:r.venue,location:r.location}))).filter(x=>x.date&&x.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);
  const nav=[['overview','Overview',BarChart3],['drafts','Drafts',FileText],['finalized','Finalized',LockKeyhole],['sent','Sent',Send]];
  return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">VC</div><div><strong>Vocal Contracts</strong><span>Artist agreement workspace</span></div></div><button className="primary" onClick={newContract}><FilePlus2 size={17}/> New contract</button></header><main className="dashboard"><div className="dash-heading"><p className="eyebrow">WORKSPACE</p><h1>{view==='overview'?'Overview':'Contracts'}</h1><p className="muted">{view==='overview'?'A clear view of your agreement pipeline and booked work.':'Create, manage and prepare professional vocal artist agreements.'}</p></div><div className="tabs">{nav.map(([key,label,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}><Icon size={14}/>{label}{key!=='overview'&&<b>{key==='drafts'?drafts:key==='finalized'?finalized:sent}</b>}</button>)}<label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contracts"/>{query&&<X size={15} onClick={()=>setQuery('')}/>}</label></div>{view==='overview'?<Overview contracts={allContracts} booked={booked} upcoming={upcoming} setView={setView} edit={edit}/>:contracts.length===0?<div className="empty"><FileText size={34}/><h2>No {view} yet</h2><p>{view==='sent'?'Finalized agreements you deliver will appear here.':'Start a new contract and your work will be saved locally in this browser.'}</p><button className="primary" onClick={newContract}><FilePlus2 size={17}/> Create contract</button></div>:<div className="contract-list">{contracts.map(c=><div className="contract-row" key={c.id} onClick={()=>edit(c)}><div className="doc-icon"><FileText size={19}/></div><div className="row-main"><strong>{c.eventName||'Untitled event'}</strong><span>{c.artistName||'Artist not set'} · {c.clientName||'Client not set'}</span></div><div className="row-meta"><span>{c.status==='draft'?'Draft':c.status==='sent'?'Sent':'Finalized'}</span><small>{new Date(c.updatedAt).toLocaleDateString()}</small></div><button className="icon-btn danger" onClick={e=>{e.stopPropagation();remove(c.id)}}><Trash2 size={16}/></button></div>)}</div>}</main></div>}

function Overview({contracts,booked,upcoming,setView,edit}){const total=contracts.length,drafts=contracts.filter(c=>c.status==='draft').length,finalized=contracts.filter(c=>c.status==='finalized').length,sent=contracts.filter(c=>c.status==='sent').length;return <div className="overview-grid"><div className="analytics-cards"><button onClick={()=>setView('drafts')}><span>Drafts</span><strong>{drafts}</strong><small>Needs completion</small></button><button onClick={()=>setView('finalized')}><span>Finalized</span><strong>{finalized}</strong><small>Ready for delivery</small></button><button onClick={()=>setView('sent')}><span>Sent</span><strong>{sent}</strong><small>Delivered agreements</small></button><div className="analytics-card"><span>Booked value</span><strong>${booked.toLocaleString('en-CA',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><small>Finalized + sent contracts</small></div></div><div className="overview-columns"><section className="overview-panel"><div className="panel-head"><div><p className="eyebrow">UPCOMING</p><h2>Performance schedule</h2></div><button className="text-button" onClick={()=>setView('finalized')}>View finalized</button></div>{upcoming.length?<div className="upcoming-list">{upcoming.map((x,i)=><button key={`${x.contract.id}-${i}`} onClick={()=>edit(x.contract)}><span>{new Date(`${x.date}T12:00:00`).toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'})}</span><strong>{x.venue||'Venue not set'}</strong><small>{x.location||'Location not set'} · {x.contract.eventName||'Untitled event'}</small></button>)}</div>:<div className="overview-empty">No upcoming performances scheduled.</div>}</section><section className="overview-panel"><div className="panel-head"><div><p className="eyebrow">PIPELINE</p><h2>Agreement activity</h2></div><span className="total-count">{total} total</span></div><div className="pipeline-rows"><div><span>Drafts</span><b>{drafts}</b><i style={{width:`${total?drafts/total*100:0}%`}}/></div><div><span>Finalized</span><b>{finalized}</b><i style={{width:`${total?finalized/total*100:0}%`}}/></div><div><span>Sent</span><b>{sent}</b><i style={{width:`${total?sent/total*100:0}%`}}/></div></div><p className="overview-note">Use the tabs above to move between your active drafting pipeline and completed agreements.</p></section></div></div>}

function Editor({contract,persist,saved,back,finalize,print,gmail}){
  const totals=useMemo(()=>calculate(contract),[contract]),report=useMemo(()=>strengthCheck(contract),[contract]),validation=useMemo(()=>validateContract(contract),[contract]);
  const update=(key,value)=>persist({...contract,[key]:value});
  const jumpToSection=id=>{const target=document.getElementById(id);if(!target)return;target.scrollIntoView({behavior:'smooth',block:'start'});target.classList.remove('strength-target');requestAnimationFrame(()=>{target.classList.add('strength-target');window.setTimeout(()=>target.classList.remove('strength-target'),1400)})};
  const rows=performanceRows(contract),model=compensationModel(contract);
  const syncFirst=next=>{const first=next[0]||newPerformance();return {...contract,performances:next,eventDate:first.date,venue:first.venue,location:first.location,performanceTime:first.performanceTime,callTime:first.callTime,duration:first.duration,sets:first.sets,breakMinutes:first.breakMinutes,soundcheckIncluded:first.soundcheckIncluded,soundcheckMinutes:first.soundcheckMinutes}};
  const updatePerformance=(i,key,value)=>persist(syncFirst(rows.map((r,index)=>index===i?{...r,[key]:value}:r)));
  const addPerformance=()=>persist({...contract,performances:[...rows,newPerformance()]});
  const duplicatePerformance=i=>persist({...contract,performances:[...rows,{...rows[i],id:crypto.randomUUID(),fee:model==='perPerformance'?rows[i].fee:''}]});
  const removePerformance=i=>{if(rows.length===1)return;persist(syncFirst(rows.filter((_,index)=>index!==i)))};
  const toggleService=s=>update('services',contract.services.includes(s)?contract.services.filter(x=>x!==s):[...contract.services,s]);
  const addRehearsal=()=>update('rehearsals',[...contract.rehearsals,{id:crypto.randomUUID(),date:'',start:'',end:'',hours:''}]);
  const updateRehearsal=(id,key,value)=>update('rehearsals',contract.rehearsals.map(r=>r.id===id?{...r,[key]:value}:r));
  const removeRehearsal=id=>update('rehearsals',contract.rehearsals.filter(r=>r.id!==id));
  const mediaCount=['allowPhotography','allowVideo','allowLivestream','allowBroadcast','allowPromoClips','allowCommercialUse','allowAI','allowVoiceCloning'].filter(k=>contract[k]).length;
  return <div className="editor-shell"><header className="editor-bar"><button className="back" onClick={back}><ChevronLeft size={18}/> Contracts</button><div className="editor-title"><strong>{contract.eventName||'New contract'}</strong><span>{saved?'Saved locally':'Saving…'}</span></div><div className="editor-actions"><button className="secondary" onClick={print}><Printer size={16}/> PDF / Print</button><button className="secondary" onClick={gmail}><Mail size={16}/> Gmail</button><button className="primary" onClick={finalize}><LockKeyhole size={16}/> Finalize</button></div></header><div className="workspace"><aside className="form-panel"><StrengthPanel report={report} validation={validation} onJump={jumpToSection}/>
    <Section id="client-section" title="Client information"><Field label="Client / organization *" value={contract.clientName} onChange={v=>update('clientName',v)}/><div className="two"><Field label="Contact name" value={contract.clientContact} onChange={v=>update('clientContact',v)}/><Field label="Email *" type="email" value={contract.clientEmail} onChange={v=>update('clientEmail',v)}/></div><Field label="Phone" value={contract.clientPhone} onChange={v=>update('clientPhone',v)}/></Section>
    <Section id="artist-section" title="Artist"><Field label="Artist name *" value={contract.artistName} onChange={v=>update('artistName',v)}/><div className="two"><Field label="Artist email" type="email" value={contract.artistEmail} onChange={v=>update('artistEmail',v)}/><Field label="Artist phone" value={contract.artistPhone} onChange={v=>update('artistPhone',v)}/></div><Field label="Artist / business name" value={contract.artistBusinessName} onChange={v=>update('artistBusinessName',v)}/><Field label="Artist address" value={contract.artistAddress} onChange={v=>update('artistAddress',v)}/></Section>
    <Section id="event-section" title="Event & performance"><Field label="Tour / event name *" value={contract.eventName} onChange={v=>update('eventName',v)}/><p className="helper">Build the complete schedule first. Every date, venue, city and performance time becomes an independent line item in the agreement.</p><div className="performance-schedule">{rows.map((r,i)=><div className="performance-card" key={r.id}><div className="performance-card-head"><div><span className="performance-label">PERFORMANCE {String(i+1).padStart(2,'0')}</span><strong>{r.date?new Date(`${r.date}T12:00:00`).toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'}):'New date'}{r.venue?` · ${r.venue}`:''}</strong></div><div className="performance-card-actions"><button type="button" className="icon-btn" onClick={()=>duplicatePerformance(i)} title="Duplicate date"><Copy size={14}/></button>{rows.length>1&&<button type="button" className="icon-btn danger" onClick={()=>removePerformance(i)} title="Remove date"><Trash2 size={14}/></button>}</div></div><div className="two"><Field label="Performance date *" type="date" value={r.date} onChange={v=>updatePerformance(i,'date',v)}/><Field label="Performance time *" type="time" value={r.performanceTime} onChange={v=>updatePerformance(i,'performanceTime',v)}/></div><div className="two"><Field label="Venue *" value={r.venue} onChange={v=>updatePerformance(i,'venue',v)}/><Field label="City / location *" value={r.location} onChange={v=>updatePerformance(i,'location',v)}/></div><div className="two"><Field label="Call time" type="time" value={r.callTime} onChange={v=>updatePerformance(i,'callTime',v)}/><Field label="Duration" value={r.duration} onChange={v=>updatePerformance(i,'duration',v)}/></div>{model==='perPerformance'&&<Field label="Performance fee" type="number" value={r.fee} onChange={v=>updatePerformance(i,'fee',v)}/>}</div>)}</div><button type="button" className="add-row" onClick={addPerformance}><Plus size={14}/> Add another performance date</button></Section>
    <Section id="services-section" title="Services"><div className="service-grid">{SERVICE_OPTIONS.map(s=><button type="button" className={`service ${contract.services.includes(s)?'selected':''}`} key={s} onClick={()=>toggleService(s)}><span>{contract.services.includes(s)?'✓':''}</span>{s}</button>)}</div></Section>
    <Section id="payment-section" title="Compensation & payment"><div className="two"><Field label="Compensation model" type="select" value={model} onChange={v=>update('compensationModel',v)} options={[['package','Package fee'],['perPerformance','Per-performance fees']]}/>{model==='package'?<Field label="Performance fee" type="number" value={contract.performanceFee} onChange={v=>update('performanceFee',v)}/>:<div className="notice-card">Each scheduled performance carries its own fee.</div>}</div><div className="two"><Field label="Deposit amount" type="number" value={contract.depositAmount} onChange={v=>update('depositAmount',v)}/><Field label="Deposit due" value={contract.depositDue} onChange={v=>update('depositDue',v)}/></div><Field label="Balance due" value={contract.balanceDue} onChange={v=>update('balanceDue',v)}/><div className="total-card"><span>Total performance compensation</span><strong>${totals.performance.toFixed(2)}</strong></div></Section>
    <Section id="rehearsal-section" title="Rehearsals"><button type="button" className="add-row" onClick={addRehearsal}><Plus size={14}/> Add rehearsal</button>{contract.rehearsals.map(r=><div className="rehearsal" key={r.id}><Field label="Date" type="date" value={r.date} onChange={v=>updateRehearsal(r.id,'date',v)}/><Field label="Start" type="time" value={r.start} onChange={v=>updateRehearsal(r.id,'start',v)}/><Field label="End" type="time" value={r.end} onChange={v=>updateRehearsal(r.id,'end',v)}/><Field label="Hours" type="number" value={r.hours} onChange={v=>updateRehearsal(r.id,'hours',v)}/><button className="icon-btn danger" onClick={()=>removeRehearsal(r.id)}><Trash2 size={15}/></button></div>)}</Section>
    <Section id="cancellation-section" title="Cancellation"><Field label="Cancellation schedule" type="select" value={contract.cancellationSchedule} onChange={v=>update('cancellationSchedule',v)} options={[['standard','Standard artist-protective schedule'],['custom','Custom terms']]}/>{contract.cancellationSchedule==='custom'&&<Field label="Custom cancellation terms" type="textarea" value={contract.cancellationCustom} onChange={v=>update('cancellationCustom',v)}/>}</Section>
    <Section id="media-section" title="Media & rights"><div className="toggle-list">{[['allowPhotography','Photography'],['allowVideo','Video recording'],['allowLivestream','Livestream'],['allowBroadcast','Broadcast'],['allowPromoClips','Promotional clips'],['allowCommercialUse','Commercial use'],['allowAI','AI training'],['allowVoiceCloning','Voice cloning']].map(([k,l])=><label className="toggle" key={k}><input type="checkbox" checked={!!contract[k]} onChange={e=>update(k,e.target.checked)}/><span className="toggle-ui"/><span>{l}</span></label>)}</div>{contract.allowCommercialUse&&<Field label="Media compensation" type="number" value={contract.mediaCompensation} onChange={v=>update('mediaCompensation',v)}/>}</Section>
    <Section id="travel-section" title="Travel & expenses"><div className="two"><Field label="Travel amount" type="number" value={contract.travelAmount} onChange={v=>update('travelAmount',v)}/><Field label="Accommodation" type="number" value={contract.accommodationAmount} onChange={v=>update('accommodationAmount',v)}/></div><div className="two"><Field label="Per diem" type="number" value={contract.perDiem} onChange={v=>update('perDiem',v)}/><Field label="Parking" type="number" value={contract.parkingAmount} onChange={v=>update('parkingAmount',v)}/></div></Section>
    <Section id="safety-section" title="Venue & safety"><Field label="Venue contact" value={contract.venueContact} onChange={v=>update('venueContact',v)}/><Field label="Production contact" value={contract.productionContact} onChange={v=>update('productionContact',v)}/><Field label="Safety requirements" type="textarea" value={contract.safetyRequirements} onChange={v=>update('safetyRequirements',v)}/></Section>
    <Section id="additional-section" title="Additional terms"><div className="two"><Field label="Governing jurisdiction" value={contract.governingJurisdiction} onChange={v=>update('governingJurisdiction',v)}/></div><Field label="Additional terms" type="textarea" value={contract.additionalTerms} onChange={v=>update('additionalTerms',v)}/></Section>
    </aside><main className="preview-panel"><div className="preview-label"><span>LIVE CONTRACT PREVIEW</span><small>{contract.number}</small></div><div className="contract-paper" dangerouslySetInnerHTML={{__html:renderContract(contract)}}/></main></div></div>;
}

function Section({id,title,children}){return <section id={id} className="form-section"><h2>{title}</h2>{children}</section>}
function Field({label,type='text',value,onChange,options}){if(type==='textarea')return <label className="field"><span>{label}</span><textarea value={value||''} onChange={e=>onChange(e.target.value)}/></label>;if(type==='select')return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>;return <label className="field"><span>{label}</span><input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function StrengthPanel({report,validation,onJump}){return <div className={`strength-panel ${report.blockers.length?'needs-work':'ready'}`}><div className="strength-head"><div><p className="eyebrow">STRENGTH CHECK</p><strong>Agreement readiness</strong></div><div className="strength-score"><span>{report.score}</span><small>/100</small></div></div><div className="strength-bar"><span style={{width:`${report.score}%`}}/></div>{report.blockers.length>0&&<div className="strength-alert"><AlertTriangle size={14}/><div><strong>{report.blockers.length} required items need attention</strong><span>Click an item below to jump to the relevant section.</span></div></div>}<div className="strength-list">{report.checks.map(x=><button key={x.key} className={`strength-item ${x.ok?'ok':'warn'}`} onClick={()=>({parties:'client-section',event:'event-section',scope:'services-section',fee:'payment-section',payment:'payment-section',overtime:'payment-section',cancellation:'cancellation-section',media:'media-section',safety:'safety-section',travel:'travel-section',jurisdiction:'additional-section',ai:'media-section',commercial:'media-section'}[x.key]&&onJump({parties:'client-section',event:'event-section',scope:'services-section',fee:'payment-section',payment:'payment-section',overtime:'payment-section',cancellation:'cancellation-section',media:'media-section',safety:'safety-section',travel:'travel-section',jurisdiction:'additional-section',ai:'media-section',commercial:'media-section'}[x.key]))}><span className="strength-icon">{x.ok?<Check size={13}/>:<CircleAlert size={13}/>}</span><span className="strength-copy"><strong>{x.label}</strong><span>{x.detail}</span></span>{!x.ok&&<span className="strength-action">Review</span>}</button>)}</div><p className="strength-note">Completeness safeguard, not a legal opinion.</p></div>}
